name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Lean
        run: |
          wget https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -O elan-init.sh
          bash elan-init.sh -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Initialize Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Run lean tests
        run: |
          cd tests/lean-tests
          lake update
          lake build
          ./build/bin/lean-tests
      
